name: Build open-dmr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: go build -v
      working-directory: app

    - name: Test
      run: go test -v
      working-directory: app

    - name: Stage packaging area
      run: mkdir staging

    - name: Download data (temp snippet for now)
      run: mv app/test_data/snippet.xml.zip ./data.zip && mv app/open-dmr staging/

    - name: Load data into DB
      run: ./open-dmr -load ../data.zip
      working-directory: staging

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mj3052/open-dmr:latest
        context: staging/
        file: deployment.dockerfile

    # - name: Zip DB
    #   run: zip -r database.zip database/

    # - name: DB Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: database
    #     path: database.zip