name: Process DMR data

on:
  # workflow_dispatch:
  # schedule:
  #   # Monday morning 3 o clock
  #   - cron:  '0 3 * * 1'

  push:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  DB:
    runs-on: ubuntu-latest
    steps:

    - name: apt
      run: sudo apt-get update && sudo apt-get install git

    - name: Build deps
      run: git clone https://github.com/estraier/tkrzw.git && cd tkrzw && ./configure --enable-opt-native --enable-most-features && make && sudo make install && cd ../

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: go build -v
      working-directory: app

    - name: Test
      run: go test -v
      working-directory: app

    - name: Stage packaging area
      run: mkdir staging && mv app/open-dmr staging/

    # - name: Install data deps
    #   run: sudo apt -y install aria2 lftp

    # - name: Download data (full)
    #   run: ./download_data.sh

    - name: Load data into DB
      # run: ./open-dmr -load ../data.zip
      run: ./open-dmr -load ../test_data/snippet.xml.zip
      working-directory: staging

    - name: Tar files
      run: tar -cvf db.tar staging/badger.db

    - name: DB Artifact
      uses: actions/upload-artifact@v3
      with:
        name: database
        path: db.tar